apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: main
  annotations:
    pipelinesascode.tekton.dev/on-event: "[push]"
    pipelinesascode.tekton.dev/on-target-branch: "main"
    pipelinesascode.tekton.dev/task: "[git-clone, 
    https://raw.githubusercontent.com/stakater/tekton-catalog/main/stakater-create-git-tag/rendered/stakater-create-git-tag-0.0.7.yaml, 
    https://raw.githubusercontent.com/stakater/tekton-catalog/main/stakater-code-linting/rendered/stakater-code-linting-0.0.3.yaml, 
    https://raw.githubusercontent.com/stakater/tekton-catalog/main/stakater-kube-linting/rendered/stakater-kube-linting-0.0.4.yaml, 
    https://raw.githubusercontent.com/stakater/tekton-catalog/main/stakater-unit-test/rendered/stakater-unit-test-0.0.5.yaml, 
    https://raw.githubusercontent.com/stakater/tekton-catalog/main/stakater-sonarqube-scan/rendered/stakater-sonarqube-scan-0.0.5.yaml, 
    https://raw.githubusercontent.com/stakater/tekton-catalog/main/stakater-buildah/rendered/stakater-buildah-0.0.18.yaml, 
    https://raw.githubusercontent.com/stakater/tekton-catalog/main/stakater-trivy-scan/rendered/stakater-trivy-scan-0.0.3.yaml,
    https://raw.githubusercontent.com/stakater/tekton-catalog/main/stakater-rox-image-scan/rendered/stakater-rox-image-scan-0.0.4.yaml, 
    https://raw.githubusercontent.com/stakater/tekton-catalog/main/stakater-rox-deployment-check/rendered/stakater-rox-deployment-check-0.0.4.yaml, 
    https://raw.githubusercontent.com/stakater/tekton-catalog/main/stakater-rox-image-check/rendered/stakater-rox-image-check-0.0.4.yaml, 
    https://raw.githubusercontent.com/stakater/tekton-catalog/main/stakater-checkov-scan/rendered/stakater-checkov-scan-0.0.3.yaml,
    https://raw.githubusercontent.com/stakater/tekton-catalog/main/stakater-github-update-cd-repo/rendered/stakater-github-update-cd-repo-0.0.7.yaml, 
    https://raw.githubusercontent.com/stakater/tekton-catalog/main/stakater-push-main-tag/rendered/stakater-push-main-tag-0.0.6.yaml,
    https://raw.githubusercontent.com/stakater/tekton-catalog/main/stakater-helm-push/rendered/stakater-helm-push-0.0.12.yaml]"
    pipelinesascode.tekton.dev/max-keep-runs: "2"

spec:
  params:
    - name: repo_url
      value: "git@github.com:notstakater/stakater-nordmart-review-api.git"
    - name: git_revision
      value: {{revision}}
    - name: repo_path
      value: {{repo_name}}
    - name: image_registry
      value: nexus-docker-stakater-nexus.apps.tno1-ams.s9nghh76.lab.kubeapp.cloud/stakater-nordmart-review-api
    - name: helm_registry
      value: >-
        https://nexus-helm-stakater-nexus.apps.tno1-ams.s9nghh76.lab.kubeapp.cloud/repository/helm-charts/
  pipelineSpec:
    params:
      - name: repo_url
      - name: git_revision
      - name: repo_path
      - name: image_registry
      - name: helm_registry
    workspaces:
      - name: source
      - name: ssh-directory

    tasks:
      - name: fetch-repository
        taskRef:
          name: git-clone
          kind: ClusterTask
        workspaces:
          - name: output
            workspace: source
          - name: ssh-directory
            workspace: ssh-directory
        params:
          - name: depth
            value: "0"
          - name: url
            value: $(params.repo_url)
          - name: revision
            value: $(params.git_revision)

      - name: create-git-tag
        runAfter:
          - fetch-repository
        taskRef:
          name: stakater-create-git-tag-0.0.7
          kind: Task
        params:
          - name: PR_NUMBER
            value: "NA"
          - name: GIT_REVISION
            value: $(params.git_revision)
        workspaces:
          - name: source
            workspace: source
          - name: ssh-directory
            workspace: ssh-directory

      - name: code-linting
        runAfter:
          - create-git-tag
        taskRef:
          name: stakater-code-linting-0.0.3
          kind: Task
        workspaces:
          - name: source
            workspace: source

      - name: kube-linting
        runAfter:
          - create-git-tag
        taskRef:
          name: stakater-kube-linting-0.0.4
          kind: Task
        params:
          - name: FILE
            value: manifest.yaml
          - name: DEPLOYMENT_FILES_PATH
            value: deploy
          - name: NAMESPACE
            value: arsenal-build
        workspaces:
          - name: source
            workspace: source

      - name: unit-test
        runAfter:
          - code-linting
          - kube-linting
        taskRef:
          name: stakater-unit-test-0.0.5
          kind: Task
        workspaces:
          - name: source
            workspace: source

      - name: sonarqube-scan
        runAfter:
          - unit-test
        taskRef:
          name: stakater-sonarqube-scan-0.0.5
          kind: Task
        params:
          - name: SONAR_HOST_URL
            value: https://sonarqube-stakater-sonarqube.apps.tno1-ams.s9nghh76.lab.kubeapp.cloud
          - name: SONAR_PROJECT_KEY
            value: $(params.repo_path)
          - name: SONAR_LOGIN
        workspaces:
          - name: source
            workspace: source

      - name: buildah
        runAfter:
          - unit-test
        taskRef:
          name: stakater-buildah-0.0.18
          kind: Task
        params:
          - name: IMAGE
            value: $(params.image_registry):$(tasks.create-git-tag.results.GIT_TAG)
          - name: TLSVERIFY
            value: "false"
          - name: FORMAT
            value: "docker"
          - name: BUILD_IMAGE
            value: "true"
          - name: IMAGE_REGISTRY
            value: $(params.image_registry)
          - name: CURRENT_GIT_TAG
            value: $(tasks.create-git-tag.results.CURRENT_GIT_TAG)
        workspaces:
          - name: source
            workspace: source

      - name: trivy-scan
        runAfter:
          - buildah
          - sonarqube-scan
        taskRef:
          name: stakater-trivy-scan-0.0.3
          kind: Task
        params:
          - name: IMAGE
            value: $(params.image_registry):$(tasks.create-git-tag.results.GIT_TAG)
        workspaces:
          - name: source
            workspace: source

      - name: checkov-scan
        runAfter:
          - buildah
          - sonarqube-scan
        taskRef:
          name: stakater-checkov-scan-0.0.3
          kind: Task
        workspaces:
          - name: source
            workspace: source

      - name: helm-push
        runAfter:
          - trivy-scan
          - checkov-scan
        taskRef:
          name: stakater-helm-push-0.0.12
          kind: Task
        params:
          - name: PR_NUMBER
            value: "NA"
          - name: REPO_PATH
            value: $(params.repo_path)
          - name: GIT_REVISION
            value: $(params.git_revision)
          - name: REGISTRY
            value: $(params.helm_registry)
          - name: SEM_VER
            value: $(tasks.create-git-tag.results.GIT_TAG)
        workspaces:
          - name: source
            workspace: source
      - name: update-cd-repo
        runAfter:
          - helm-push
        taskRef:
          kind: Task
          name: stakater-github-update-cd-repo-0.0.7
        params:
          - name: IMAGE_TAG
            value: $(tasks.create-git-tag.results.GIT_TAG)
          - name: IMAGE_NAME
            value: $(params.image_registry)
          - name: PR_NUMBER
            value: "NA"
          - name: REPO_PATH
            value: $(params.repo_path)
          - name: GIT_REVISION
            value: main
          - name: NAMESPACE
            value: arsenal-dev
          - name: ENVIRONMENT
            value: dev
          - name: HELM_REGISTRY
            value: $(params.helm_registry)
          - name: CD_REPO_URL
            value: git@github.com:notstakater/webinar-apps-gitops-config.git
        workspaces:
          - name: source
            workspace: source
          - name: ssh-directory
            workspace: cd-ssh-creds

      - name: push-main-tag
        runAfter:
          - update-cd-repo
        taskRef:
          kind: Task
          name: stakater-push-main-tag-0.0.6
        params:
          - name: PR_NUMBER
            value: "NA"
          - name: GIT_REVISION
            value: $(params.git_revision)
          - name: IMAGE_TAG
            value: $(tasks.create-git-tag.results.GIT_TAG)
        workspaces:
          - name: source
            workspace: source
          - name: ssh-directory
            workspace: ssh-directory

  workspaces:
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
    - name: ssh-directory
      secret:
        secretName: nordmart-api-ssh-creds
    - name: cd-ssh-creds
      secret:
        secretName: cd-ssh-creds
